name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set date as version
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          no-cache: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/blinkospace/blinko:latest
            ghcr.io/${{ github.repository_owner }}/blinkospace/blinko:${{ env.VERSION }}
